### ISSUE TITLE
Complete Keyboard input in DateBox / InputDate seems impossible

### ISSUE THREAD

**Issue by cyrilmhansen** [Putnami/putnami-web-toolkit#110]
(Tested with current chrome on windows)
The inputDate element is composed of a popup calendar element and an input text field

When a date is already displayed, one can click on a date part, say the day part, and type the new numeric value or select it by using arrow keys.

When we use focus navigation and directly type into the text field, the input is used to replace the year value only. My application uses the french format dd/MM/yyyy and I would like my client to be able to input a date in an empty field using only the keyboard  : ie tab 15 01 2015 for 15/01/2015 (Jan 15th 2015). This does not seem to be possible for now.

Is the current behavior of the text field the expected one ?

**Comment by fdumay** [comment]
Hi,
I raised 2 bugs:

* The first one is : when we enter a wrong date (eq. Feb 31) an error is thrown and the datepicker can not be opened.
* And the second is : When the field is empty, and we start to type the date then enter one separator '/' the cursor goes away and the field doesn't work anymore.

I'll try to deal with it as soon as possible.

See you
