### ISSUE TITLE
InputFile mangles non latin1 characters in filename

### ISSUE THREAD

**Issue by cyrilmhansen** [Putnami/putnami-web-toolkit#113]
I have an issue with the InputFile component when the filename contains french accentuated chars (like éà)...  After the initial upload, the filename is displayed as if the string representation was UTF-8 ('é' is two bytes) and processed as ISO-8869-1 (é is one byte). : ie 'é' becomes 'Ã©'

Note that my application is loaded from an UTF-8 web page, so the XMLHttpRequest used by InputFile is definitely expected to be UTF-8. I am not sure what encoding the following code is expecting : 

in private void handleCompleteJson(String reponseData) {
  (...)
JSONObject jsObject = JSONParser.parseLenient(reponseData).isObject();

final FileDto file = new FileDto();
-->	file.setName(jsObject.get("name").isString().stringValue());

**Comment by fdumay** [comment]
Hi, sorry for the long delay.
I've tried to reproduce that bug without success.
Is that issue is still up?

**Comment by cyrilmhansen** [comment]
Yes this issue is still visible with latest published snapshot (february)
Maybe I can try to make a minimal war to display the problem. Maybe It is my tomcat configuration which is incorrect, but I am clueless for now.

**Comment by fdumay** [comment]
Thank to your sample project, I found the trouble.
To solve that issue you need to force the encoding as UTF-8.
To do it, you must declare a CharacterEncodingFilter in your spring configuration :

```
	@Bean
	public CharacterEncodingFilter characterEncodingFilter() {
		CharacterEncodingFilter characterEncodingFilter = new CharacterEncodingFilter();
		characterEncodingFilter.setEncoding("UTF-8");
		characterEncodingFilter.setForceEncoding(true);
		return characterEncodingFilter;
	}
```

**Comment by cyrilmhansen** [comment]
Indeed that does the trick.
