### ISSUE TITLE
Adding src from different gradle module

### ISSUE THREAD

**Issue by Kravs** [Putnami/putnami-web-toolkit#132]
How to add my sources from different module?
Sorry if it is obvious, but for now I can't find it in documentation :(

**Comment by fdumay** [comment]
Hi Antin,

You can look at the multimodules sample in putnami-gradle-plugin.
https://github.com/Putnami/putnami-gradle-plugin/tree/master/samples/pgp-sample-multimodules

To make a module you may apply the plugin fr.putnami.gwt-lib. Please have a look at:
https://github.com/Putnami/putnami-gradle-plugin

If it's not enough, let me know.

Cheers

**Comment by Kravs** [comment]
Thanks for so quick response!
 I sat that samples... 
Could I use domain project without adding 'fr.putnami.gwt-lib' plugin ?

**Comment by fdumay** [comment]
Basically you can, but some extra gradle conf for doing almost the same thing that this plugin does.

To do so, you should add the below lines in your build.gradle:

```
//Include all non java (like *.gwt.xml) files from 'src/main/java' folder in resources
sourceSets.main.resources.srcDir 'src/main/java'

// Add all sources in jar (needed for GWT compilation using this library
jar {
	from sourceSets.main.allJava
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}
```

note: the those lines also build the source artifact, it's not required.

**Comment by Kravs** [comment]
Ok, got it, probably I missed something..

 should I add gwt.xml to my domain project?
I just want to reuse existing project, and trying not to modify it)

**Comment by fdumay** [comment]
Your domain project must at least provide the java sources. for that you have 2 choices:

1 - Include sources in the jar:
```
sourceSets.main.resources.srcDir 'src/main/java'
jar {
    from sourceSets.main.allJava
}
```
2 - use the source artifact
```
task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}
artifacts {
    archives sourcesJar
}
```

Your are not required to add any gwt.xml, in this cas you must add it in the webapp project. Be sure to put it in the right package, and that this one properly includes the sources to gwt compiler.

**Comment by Kravs** [comment]
Ok, thanks for help,I will try :)

**Comment by fdumay** [comment]
Happy to help.
So I close this issues.

**Comment by Kravs** [comment]
Thank you for help :)
